name: Mad 360 Photography
favicon: null
layout_spectrum: 0.9721754
typography_spectrum: 0.9818514576181769
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#060606'
    - '#a0a0a0'
    - '#747474'
    - '#ca782c'
  brandStrength: 0.8153457
  lightness: 0.1425471368711442
  saturation: 0.5626737824641168
  rhythmicContrast: 0.6693079757969826
purpose: []
