name: Mad 360 Photography
favicon: null
layout_spectrum: 0.50167
typography_spectrum: 0.9818514576181769
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#c8d7f5'
    - '#1767d8'
    - '#95b4eb'
    - '#0b33a4'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.2875211
purpose: []
